FORMAT: 1A
HOST: http://localhost:3000

# user API
Welcome to the user API.

# users action [/users]

## Create user [POST]
## Get users [GET]


# user action [/users/{id}]

## Get user [GET]
## Update user [PUT]
## Delete user [DELETE]


# Data Structures
## users (object)
